### ISSUE TITLE
Request for paper update

### ISSUE THREAD

**Issue by huanngzh** [cwchenwang/awesome-3d-diffusion#10]
We would be grateful if you can add our paper _EpiDiff_, a multi-view diffusion model.
Title: EpiDiff: Enhancing Multi-View Synthesis via Localized Epipolar-Constrained Diffusion
Paper: https://arxiv.org/abs/2312.06725
Project page: https://huanngzh.github.io/EpiDiff/

**Comment by cwchenwang** [comment]
Updated.
