### ISSUE TITLE
Nice repo!

### ISSUE THREAD

**Issue by thuwzy** [cwchenwang/awesome-3d-diffusion#2]
Thank you for your nice work on curating the list for 3D diffusion! Can you consider adding our work into the repo? 

ProlificDreamer: High-Fidelity and Diverse Text-to-3D Generation with Variational Score Distillation, NeurIPS 2023. 
Project page: https://ml.cs.tsinghua.edu.cn/prolificdreamer/

Thank you!

**Comment by cwchenwang** [comment]
Yes, of course. This is an absolutely amazing work, but somehow I forgot to add it. Apologize for that. I have added it now.

**Comment by thuwzy** [comment]
Thank you :)
